services:
  - type: web
    name: nvite-app
    env: node
    plan: free
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: nvite-app
          property: port
      - key: JSONBIN_BIN_ID
        sync: false
      - key: JSONBIN_API_KEY
        sync: false

